# Generated by Django 3.1.4 on 2022-03-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='senior_type',
            field=models.CharField(default='PowerLifting', max_length=50),
        ),
    ]
