# Generated by Django 3.1.4 on 2022-03-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userprofile_senior_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
