# Generated by Django 3.1.4 on 2022-03-14 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_auto_20220314_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True)),
                ('training_style', models.CharField(default='PowerLifting', max_length=50)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(default='Male', max_length=6)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
