# Generated by Django 3.1.4 on 2022-03-14 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20220314_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='countInStock',
        ),
        migrations.AddField(
            model_name='order',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trainee'),
        ),
        migrations.AddField(
            model_name='order',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trainer'),
        ),
        migrations.AddField(
            model_name='review',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trainee'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
