# Generated by Django 4.0.2 on 2022-03-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220314_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='height',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='weight',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
