# Generated by Django 4.0.2 on 2022-03-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220314_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to='photos'),
        ),
    ]
