# Generated by Django 4.0.2 on 2022-03-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_trainee_height_alter_trainee_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
