# Generated by Django 4.0.2 on 2022-03-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_trainer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='height',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='weight',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
