# Generated by Django 4.0.2 on 2022-03-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_trainee_avatar_alter_trainee_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='height',
        ),
        migrations.AddField(
            model_name='trainee',
            name='heightft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='heightin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
