# Generated by Django 4.0.2 on 2022-04-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_trainee_height_trainee_heightft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='image',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='trainer',
            name='image1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Description1', models.TextField(blank=True, null=True)),
                ('Description2', models.TextField(blank=True, null=True)),
                ('Description3', models.TextField(blank=True, null=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_message', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trainee')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trainer')),
            ],
        ),
    ]
