# Generated by Django 4.0.2 on 2022-04-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_image_trainer_avatar_trainer_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='video',
            field=models.FileField(default='video.mp4', upload_to='video/%y'),
        ),
    ]
