# Generated by Django 4.0.2 on 2022-04-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_trainer_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='video',
            field=models.FileField(default='video.mp4', upload_to='video/'),
        ),
    ]
