# Generated by Django 4.0.2 on 2022-04-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_trainer_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Description1',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Description2',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Description3',
            new_name='description3',
        ),
    ]
