# Generated by Django 4.0.2 on 2022-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_description1_payment_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
