# Generated by Django 4.0.2 on 2022-04-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_chat_isaccepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_message', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trainee')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trainer')),
            ],
        ),
    ]
