# Generated by Django 4.0.2 on 2022-04-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_file_eof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='eof',
            field=models.BooleanField(),
        ),
    ]
