# Generated by Django 4.0.2 on 2022-04-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_file_existingpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='image9',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='video',
        ),
    ]
