# Generated by Django 4.0.2 on 2022-04-11 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_rename_price_payment_price1_payment_price2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='base.trainer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='base.trainer'),
        ),
    ]
