# Generated by Django 4.0.2 on 2022-04-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_note_note_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='isAccepted',
        ),
    ]
