# Generated by Django 4.0.2 on 2022-04-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_chat_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='trainee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='base.trainee'),
        ),
    ]
