# Generated by Django 4.0.2 on 2022-04-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_messages_issender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='isSender',
        ),
    ]
