# Generated by Django 4.0.2 on 2022-04-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_messages_issender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trainee'),
        ),
    ]
