# Generated by Django 4.0.2 on 2022-04-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_note_trainee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paidAt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='orderID',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
