# Generated by Django 4.0.2 on 2022-04-22 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_remove_order_paidat_remove_order_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='endDate',
            field=models.DateTimeField(blank=True, default=datetime.date(1900, 1, 1), null=True),
        ),
    ]
