# Generated by Django 4.0.2 on 2022-04-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_order_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='price',
        ),
    ]
